[package]
name = "resistance-civil-protection"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
bson = "2.13.0"
lettre = "0.11.11"
log = "0.4.22"
regex = "1.11.1"
serde = "1.0.216"
serde_json = "1.0.134"
tempfile = "3.17.1"
